name: flutter_fast_lib
description: A library for quickly creating flutter applications
version: 0.0.5
homepage: https://github.com/AriesHoo/flutter_fast_lib
email: AriesHoo@126.com

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  #  国际化支持
  flutter_localizations:
    sdk: flutter
  #  状态管理State
  provider: '>=5.0.0'
  #  日志打印
  logger: '>=1.0.0 <2.0.0'
  #  网络请求相关dio
  dio: '5.1.1'
  #  下拉刷新
  pull_to_refresh: '>=2.0.0 <3.0.0'
  synchronized: '>=3.0.0 <4.0.0'
  #  本地缓存sp
  shared_preferences: '>=2.0.5 <4.0.0'
  #  toast工具类
  bot_toast: '>=4.0.1'
  #  统一工具类
  common_utils: '>=2.1.0'
  decimal: '2.3.2'
  #  自适应/响应式--判定屏幕尺寸
  adaptive_breakpoints: '0.1.6'
  #  组件生命周期
  lifecycle: '0.6.0'
  # WebView
  webview_flutter: '3.0.4'
  #  设备信息
  device_info_plus: '>=3.1.1 <6.0.0'
  #  应用包信息
  package_info_plus: '>=1.3.0'
  # 文件路径获取
  path_provider: '>=2.0.2'
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: me.aries.flutter_fast_lib.flutter_fast_lib
        pluginClass: FlutterFastLibPlugin
      ios:
        pluginClass: FlutterFastLibPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
